swagger: "2.0"
info:
  description: "Very simplistic API to handle notes."
  version: "0.0.2"
  title: "Swagger"
schemes:
  -http
host: localhost:8081
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      operationId: getMe
      parameters: 
        - name: me
          description: Get the logged user
  